#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - apt-get update
  - apt install mysql-server nginx php-fpm php-mysql -y
  - sed -i "s/^bind-address.*$/bind-address            = 0.0.0.0/g" /etc/mysql/mysql.conf.d/mysqld.cnf
  - sed -i "s/^mysqlx-bind-address.*$/mysqlx-bind-address            = 0.0.0.0/g" /etc/mysql/mysql.conf.d/mysqld.cnf
  - systemctl enable mysql
  - systemctl restart mysql
#  - mysql -u root -e "CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'Pass@w0rd';GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
  - mysql -u root -e "CREATE DATABASE wordpress;"
  - mysql -u root -e "CREATE USER 'wordpress'@'%' IDENTIFIED WITH mysql_native_password BY 'Pass@w0rd';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - echo "root:Pass@w0rd" | chpasswd -c SHA512