#cloud-config
package_update: true
package_upgrade: true

write_files:
- encoding: b64
  content: ${nginxConfig}
  owner: root:root
  path: /root/nginx_proxy.conf
  permissions: '0644'

runcmd:
  - apt-get update
  - apt install nginx -y
  - rm -rf /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - cp /root/nginx_proxy.conf /etc/nginx/conf.d/nginx_proxy.conf
  - systemctl restart nginx
  - echo "root:Pass@w0rd" | chpasswd -c SHA512